export const AUTH_USER = "AUTH_USER";
export const UNAUTH_USER = "UNAUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const FETCH_PLAYERS = "FETCH_PLAYERS";
export const FETCH_PLAYERS_BY_POSITION = "FETCH_PLAYERS_BY_POSITION";
